In [1]:
import requests
import pandas as pd

In [ ]:
# Realizar al menos una consulta a una API 

base_url = "https://api-colombia.com/"
endpoint = "/api/v1/TouristicAttraction"
respuesta_api =  requests.get(base_url + endpoint)

In [3]:
# Convertir la respuesta a formato estructurado (JSON → DataFrame)
print(respuesta_api.status_code)
respuesta_api.json()
respuesta_json = respuesta_api.json()

df_api = pd.DataFrame.from_dict(respuesta_json)

200

In [4]:
df_api

,id,name,description,images,latitude,longitude,cityId,city
0,36,Hacienda napoles,La Hacienda Nápoles es el nombre que tuviera e...,[https://upload.wikimedia.org/wikipedia/common...,5.887894,-74.6418,88,"{'id': 88, 'name': 'Puerto Triunfo', 'descript..."
1,34,Santa fe de antioquia,Santa Fe de Antioquia3​ es un municipio de Col...,[https://colombia.travel/sites/default/files/s...,6.556389,-75.8275,125,"{'id': 125, 'name': 'Santafé de Antioquia', 'd..."
2,17,La ventana del mundo,La Ventana al mundo es un monumento público ub...,[https://upload.wikimedia.org/wikipedia/common...,11.03308,-74.831406,144,"{'id': 144, 'name': 'Barranquilla', 'descripti..."
3,19,Volcan del totumo,El volcán del Totumo es un cono volcánico llen...,[https://lanzateyviaja.com/wp-content/uploads/...,10.744472,-75.241403,191,"{'id': 191, 'name': 'Santa Catalina', 'descrip..."
4,4,Lago de Tota,El lago de Tota es un cuerpo de agua natural s...,[https://upload.wikimedia.org/wikipedia/common...,5.55,-72.916667,219,"{'id': 219, 'name': 'Aquitania', 'description'..."
5,26,Nevado del cocuy,"El Parque Nacional Natural Güicán, Cocuy y Chi...",[https://upload.wikimedia.org/wikipedia/common...,6.433333,-72.283333,247,"{'id': 247, 'name': 'El Cocuy', 'description':..."
6,28,Nevado del ruiz,"El Nevado del Ruiz, Volcán del Ruiz o la Mesa ...",[https://upload.wikimedia.org/wikipedia/common...,4.8925,-75.323611,337,"{'id': 337, 'name': 'Manizales', 'description'..."
7,41,Parque nacional natural Puracé,El parque nacional natural Puracé se encuentra...,[Puracé_-_Paisaje_Lago_3-_Foto_Archivo_de_Parq...,2.2,-76.35,399,"{'id': 399, 'name': 'Popayán', 'description': ..."
8,40,Centro Histórico de Popayán,El Centro Histórico de Popayán se encuentra en...,[Centro_Histórico_2.JPG (1280×960) (wikimedia....,2.43823,-76.61316,399,"{'id': 399, 'name': 'Popayán', 'description': ..."
9,3,Villa de Leyva,Villa de Leyva es un municipio colombiano ubic...,[https://travelgrafia.co/wp-content/uploads/20...,5.633056,-73.525556,592,"{'id': 592, 'name': 'Ricaurte', 'description':..."
10,2,Laguna del Cacique Guatavita,La Laguna del Cacique Guatavita se encuentra e...,[https://upload.wikimedia.org/wikipedia/common...,4.977222,-73.775556,596,"{'id': 596, 'name': 'Sesquilé', 'description':..."
11,38,Parque Jaime Duque,El parque fue desarrollado e inaugurado el 27 ...,[https://upload.wikimedia.org/wikipedia/common...,4.94769,-73.9631,613,"{'id': 613, 'name': 'Tocancipá', 'description'..."
12,15,La Catedral de Sal,La Catedral de la Sal es un recinto construido...,[https://upload.wikimedia.org/wikipedia/common...,5.01876,-74.0093,641,"{'id': 641, 'name': 'Zipaquirá', 'description'..."
13,6,Cerro Azul,Cerro Azul es un yacimiento arqueológico excav...,[https://www.colombia.co/wp-content/uploads/20...,2.529728,-72.866389,654,"{'id': 654, 'name': 'San José del Guaviare', '..."
14,12,Desierto de la Tatacoa,El Desierto de la Tatacoa es considerado como ...,[https://denomades.s3.us-west-2.amazonaws.com/...,3.23,-75.17,657,"{'id': 657, 'name': 'Neiva', 'description': 'N..."
15,37,San agustin,San Agustín es un municipio colombiano ubicado...,[https://upload.wikimedia.org/wikipedia/common...,1.879167,-76.268333,693,"{'id': 693, 'name': 'San Agustín', 'descriptio..."
16,8,Cabo de la vela,El cabo de la Vela es un accidente costero que...,[https://cdn.colombia.com/images/v2/turismo/si...,12.22,-72.15,704,"{'id': 704, 'name': 'Uribia', 'description': '..."
17,39,Jericó,"Jericó es un municipio de Colombia, situado en...",[https://upload.wikimedia.org/wikipedia/common...,5.791111,-75.785833,68,"{'id': 68, 'name': 'Jericó', 'description': ''..."
18,5,Caño Cristales,Caño Cristales es un río de Colombia que está ...,[https://www.colombia.co/wp-content/uploads/20...,2.264167,-73.794444,752,"{'id': 752, 'name': 'La Macarena', 'descriptio..."
19,13,Santuario de las lajas,El Santuario de Nuestra Señora del Rosario de ...,[https://denomades.s3.us-west-2.amazonaws.com/...,0.8055,-77.586,791,"{'id': 791, 'name': 'Ipiales', 'description': ..."
20,22,Volcan azufral,El Azufral es un volcán semiactivo ubicado en ...,[https://www.travelombia.com/wp-content/upload...,1.085264,-77.718758,823,"{'id': 823, 'name': 'Túquerres', 'description'..."
21,30,Filandia,Filandia es un municipio colombiano pertenecie...,[https://upload.wikimedia.org/wikipedia/common...,4.673333,-75.658333,889,"{'id': 889, 'name': 'Filandia', 'description':..."
22,11,Parque del cafe,El Parque del Café es un parque temático colom...,[https://upload.wikimedia.org/wikipedia/common...,4.54,-75.77,891,"{'id': 891, 'name': 'Montenegro', 'description..."
23,27,Valle del cocora,El valle de Cocora es un paisaje natural local...,[https://upload.wikimedia.org/wikipedia/common...,4.641111,-75.541389,894,"{'id': 894, 'name': 'Salento', 'description': ..."
24,24,Salento,Salento es un municipio colombiano en el depar...,[https://upload.wikimedia.org/wikipedia/common...,4.637222,-75.570833,894,"{'id': 894, 'name': 'Salento', 'description': ..."
25,16,San Andres,La isla de San Andrés (conocida también como S...,[https://upload.wikimedia.org/wikipedia/common...,12.583333,-81.7,912,"{'id': 912, 'name': 'San Andrés', 'description..."
26,23,Parque Nacional del Chicamocha,El parque está ubicado en la vía Bucaramanga -...,[https://upload.wikimedia.org/wikipedia/common...,6.7898,-73.003986,918,"{'id': 918, 'name': 'Aratoca', 'description': ..."
27,21,Barichara,Barichara es un municipio colombiano ubicado e...,[https://blog.redbus.co/wp-content/uploads/201...,6.636111,-73.223611,920,"{'id': 920, 'name': 'Barichara', 'description'..."
28,35,Buga,"Guadalajara de Buga, que es el nombre formal d...",[https://upload.wikimedia.org/wikipedia/common...,3.9,-76.301944,1087,"{'id': 1087, 'name': 'Bugalagrande', 'descript..."
29,29,Parque Arví,El Parque Regional Ecoturístico Arví es un par...,[https://upload.wikimedia.org/wikipedia/common...,6.265556,-75.496944,12,"{'id': 12, 'name': 'Medellín', 'description': ..."
30,18,Museo el Castillo,El Museo y Jardines El Castillo es un museo co...,[https://lanzateyviaja.com/wp-content/uploads/...,6.19019,-75.56954,12,"{'id': 12, 'name': 'Medellín', 'description': ..."
31,7,Guatapé,"Guatapé es un municipio de Colombia, localizad...",[https://cdn.colombia.com/images/v2/turismo/si...,6.2325,-75.15861,12,"{'id': 12, 'name': 'Medellín', 'description': ..."
32,20,Cerro de Monserrate,El cerro de Monserrate es el más conocido de l...,[https://www.colombia.co/wp-content/uploads/20...,4.605833,-74.056389,167,"{'id': 167, 'name': 'Bogotá D.C.', 'descriptio..."
33,1,Museo del oro,El Museo del Oro del Banco de la República de ...,[https://upload.wikimedia.org/wikipedia/common...,4.601919,-74.072,167,"{'id': 167, 'name': 'Bogotá D.C.', 'descriptio..."
34,32,Ciudad amurallada,La Ciudad Amurallada es el centro histórico de...,[https://2.bp.blogspot.com/-zH6Y3DoW8zQ/UgZ1Pu...,10.423611,-75.525278,210,"{'id': 210, 'name': 'Cartagena', 'description'..."
35,10,Castillo San Felipe de Barajas,El Castillo San Felipe de Barajas es una forti...,[https://upload.wikimedia.org/wikipedia/common...,10.42222,-75.53806,210,"{'id': 210, 'name': 'Cartagena', 'description'..."
36,31,Rodadero,El Rodadero es un balneario de la ciudad de Sa...,[https://upload.wikimedia.org/wikipedia/common...,11.20145,-74.22812,709,"{'id': 709, 'name': 'Santa Marta', 'descriptio..."
37,14,Ciudad Perdida,"Ciudad Perdida, también conocida como Teyuna o...",[https://javitour.com/wp-content/uploads/2015/...,11.037997,-73.925192,709,"{'id': 709, 'name': 'Santa Marta', 'descriptio..."
38,9,Parque nacional natural Tayrona,El parque nacional natural Tayrona se encuentr...,[https://upload.wikimedia.org/wikipedia/common...,11.283333,-74.183333,709,"{'id': 709, 'name': 'Santa Marta', 'descriptio..."
39,25,Parque nacional de los nevados,El Parque Nacional Natural Los Nevados se encu...,[https://3.bp.blogspot.com/-cFroLh1p7_k/WFdKQU...,4.8,-75.366667,885,"{'id': 885, 'name': 'Armenia', 'description': ..."
40,33,Cerro cristo rey,Cristo Rey es una estatua de 26 metros de altu...,[https://upload.wikimedia.org/wikipedia/common...,3.440833,-76.554167,1093,"{'id': 1093, 'name': 'Cali', 'description': 'C..."

In [5]:
df_api.head()

,id,name,description,images,latitude,longitude,cityId,city
0,36,Hacienda napoles,La Hacienda Nápoles es el nombre que tuviera e...,[https://upload.wikimedia.org/wikipedia/common...,5.887894,-74.6418,88,"{'id': 88, 'name': 'Puerto Triunfo', 'descript..."
1,34,Santa fe de antioquia,Santa Fe de Antioquia3​ es un municipio de Col...,[https://colombia.travel/sites/default/files/s...,6.556389,-75.8275,125,"{'id': 125, 'name': 'Santafé de Antioquia', 'd..."
2,17,La ventana del mundo,La Ventana al mundo es un monumento público ub...,[https://upload.wikimedia.org/wikipedia/common...,11.03308,-74.831406,144,"{'id': 144, 'name': 'Barranquilla', 'descripti..."
3,19,Volcan del totumo,El volcán del Totumo es un cono volcánico llen...,[https://lanzateyviaja.com/wp-content/uploads/...,10.744472,-75.241403,191,"{'id': 191, 'name': 'Santa Catalina', 'descrip..."
4,4,Lago de Tota,El lago de Tota es un cuerpo de agua natural s...,[https://upload.wikimedia.org/wikipedia/common...,5.55,-72.916667,219,"{'id': 219, 'name': 'Aquitania', 'description'..."

In [6]:
# Realizar limpieza y transformación de datos
df_api.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           41 non-null     int64
 1   name         41 non-null     str
 2   description  41 non-null     str
 3   images       41 non-null     object
 4   latitude     41 non-null     str
 5   longitude    41 non-null     str
 6   cityId       41 non-null     int64
 7   city         41 non-null     object
dtypes: int64(2), object(2), str(4)
memory usage: 2.7+ KB

In [7]:
print("Filas:", df_api.shape[0])
print("Columnas:", df_api.shape[1])

Filas: 41
Columnas: 8

In [8]:
print(df_api.columns.tolist())

['id', 'name', 'description', 'images', 'latitude', 'longitude', 'cityId', 'city']

In [9]:
df_api.isnull().sum()

id             0
name           0
description    0
images         0
latitude       0
longitude      0
cityId         0
city           0
dtype: int64

In [10]:
print("Registros duplicados:", df_api["id"].duplicated().sum())

Registros duplicados: 0

In [11]:
df_final = df_api.copy()

In [12]:
columnas_texto = ["name", "description", "city"]

for columna in columnas_texto:
    df_final[columna] = df_final[columna].astype(str).str.strip()

In [13]:
df_final[["name", "city"]].head()

                    name                                               city
0       Hacienda napoles  {'id': 88, 'name': 'Puerto Triunfo', 'descript...
1  Santa fe de antioquia  {'id': 125, 'name': 'Santafé de Antioquia', 'd...
2   La ventana del mundo  {'id': 144, 'name': 'Barranquilla', 'descripti...
3      Volcan del totumo  {'id': 191, 'name': 'Santa Catalina', 'descrip...
4           Lago de Tota  {'id': 219, 'name': 'Aquitania', 'description'...

In [14]:
df_final["latitude"] = pd.to_numeric(df_final["latitude"], errors="coerce")
df_final["longitude"] = pd.to_numeric(df_final["longitude"], errors="coerce")

In [15]:
print(df_final[["latitude", "longitude"]].dtypes)

latitude     float64
longitude    float64
dtype: object

In [16]:
# Transformación 
print(df_final["images"].iloc[0])

['https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/P%C3%B3rtico_Hacienda_N%C3%A1poles.JPG/800px-P%C3%B3rtico_Hacienda_N%C3%A1poles.JPG']

In [17]:
# Generar un dataset final listo para análisis
df_final["images"] = df_final["images"].apply(
    lambda x: " | ".join(x) if isinstance(x, list) else str(x)
)

In [18]:
# Cantidad de caracteres 
df_final["description_length"] = df_final["description"].str.len()

In [19]:
# Cantidad de imagenes por atractivo
df_final["number_of_images"] = df_api["images"].apply(
    lambda x: len(x) if isinstance(x, list) else 0
)

In [20]:
df_final.head()

,id,name,description,images,latitude,longitude,cityId,city,description_length,number_of_images
0,36,Hacienda napoles,La Hacienda Nápoles es el nombre que tuviera e...,https://upload.wikimedia.org/wikipedia/commons...,5.887894,-74.641800,88,"{'id': 88, 'name': 'Puerto Triunfo', 'descript...",1060,1
1,34,Santa fe de antioquia,Santa Fe de Antioquia3​ es un municipio de Col...,https://colombia.travel/sites/default/files/sa...,6.556389,-75.827500,125,"{'id': 125, 'name': 'Santafé de Antioquia', 'd...",704,1
2,17,La ventana del mundo,La Ventana al mundo es un monumento público ub...,https://upload.wikimedia.org/wikipedia/commons...,11.033080,-74.831406,144,"{'id': 144, 'name': 'Barranquilla', 'descripti...",733,1
3,19,Volcan del totumo,El volcán del Totumo es un cono volcánico llen...,https://lanzateyviaja.com/wp-content/uploads/2...,10.744472,-75.241403,191,"{'id': 191, 'name': 'Santa Catalina', 'descrip...",515,1
4,4,Lago de Tota,El lago de Tota es un cuerpo de agua natural s...,https://upload.wikimedia.org/wikipedia/commons...,5.550000,-72.916667,219,"{'id': 219, 'name': 'Aquitania', 'description'...",754,1

In [21]:
import ast

In [22]:
df_final["city"] = df_final["city"].apply(
    lambda x: ast.literal_eval(x)["name"] if isinstance(x, str) else x
)

In [23]:
# Limpiar para que City nos traiga solo el nombre de la ciudad
df_final[["name", "city"]].head()

                    name                  city
0       Hacienda napoles        Puerto Triunfo
1  Santa fe de antioquia  Santafé de Antioquia
2   La ventana del mundo          Barranquilla
3      Volcan del totumo        Santa Catalina
4           Lago de Tota             Aquitania

In [24]:
print(type(df_final["city"].iloc[0]))
print(df_final["city"].iloc[0])

<class 'str'>
Puerto Triunfo

In [25]:
print(df_final["city"].apply(type).value_counts())

city
<class 'str'>    41
Name: count, dtype: int64

In [26]:
# Validación de Dd_final
df_final.head()

,id,name,description,images,latitude,longitude,cityId,city,description_length,number_of_images
0,36,Hacienda napoles,La Hacienda Nápoles es el nombre que tuviera e...,https://upload.wikimedia.org/wikipedia/commons...,5.887894,-74.641800,88,Puerto Triunfo,1060,1
1,34,Santa fe de antioquia,Santa Fe de Antioquia3​ es un municipio de Col...,https://colombia.travel/sites/default/files/sa...,6.556389,-75.827500,125,Santafé de Antioquia,704,1
2,17,La ventana del mundo,La Ventana al mundo es un monumento público ub...,https://upload.wikimedia.org/wikipedia/commons...,11.033080,-74.831406,144,Barranquilla,733,1
3,19,Volcan del totumo,El volcán del Totumo es un cono volcánico llen...,https://lanzateyviaja.com/wp-content/uploads/2...,10.744472,-75.241403,191,Santa Catalina,515,1
4,4,Lago de Tota,El lago de Tota es un cuerpo de agua natural s...,https://upload.wikimedia.org/wikipedia/commons...,5.550000,-72.916667,219,Aquitania,754,1

In [27]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  41 non-null     int64
 1   name                41 non-null     str
 2   description         41 non-null     str
 3   images              41 non-null     str
 4   latitude            41 non-null     float64
 5   longitude           41 non-null     float64
 6   cityId              41 non-null     int64
 7   city                41 non-null     str
 8   description_length  41 non-null     int64
 9   number_of_images    41 non-null     int64
dtypes: float64(2), int64(4), str(4)
memory usage: 3.3 KB

In [28]:
df_final.isnull().sum()

id                    0
name                  0
description           0
images                0
latitude              0
longitude             0
cityId                0
city                  0
description_length    0
number_of_images      0
dtype: int64

In [29]:
# Exportar el dataset como archivo 
df_final.to_csv("atractivos_turisticos_colombia.csv", index=False)